src/main/java/no/nav/fo/veilarbperson/PersonFletter.java, src/main/java/no/nav/fo/veilarbperson/consumer/portefolje/PortefoljeService.java, src/main/java/no/nav/fo/veilarbperson/rest/PersonRessurs.java, src/test/java/no/nav/fo/veilarbperson/TestContext.java
- environment.name er ikke tilgjengelig som system property på nais
- opprettet selftest for integrasjonen
- refaktorerte til egen PortefoljeService
=> KAIZEN-0 Fikset integrasjon mot veilarbportefolje

pom.xml, src/main/java/no/nav/veilarbperson/client/pdl/PdlClientImpl.java
aktoerregister (fikset i common) og PDL
=> fiks url til helsesjekker

src/main/java/no/nav/veilarbperson/client/kodeverk/KodeverkClientImpl.java
Har en feil sak relatert til dette. Er det en spesiell grunn til at dette parameteret var sett til true?
@AlexGaard
=> Endret ekskluderUgyldige parameter for Kodeverk

nais-dev.yaml, nais-prod.yaml, src/main/resources/application.properties
TPS har byttet URL etter å ha migrert fra websphere til wildfly
=> Byttet url til TPS

src/main/java/no/nav/veilarbperson/service/PersonService.java, src/test/java/no/nav/veilarbperson/service/PersonServiceTest.java, src/test/java/no/nav/veilarbperson/service/PersonV2ServiceTest.java
=> Ny feature toggle for å aktivt slå av sjekk på nivå 4.

nais-dev.yaml, nais-prod.yaml, src/main/java/no/nav/veilarbperson/config/ClientConfig.java, src/main/java/no/nav/veilarbperson/config/EnvironmentProperties.java, src/main/resources/application.properties
TPS har byttet URL etter å ha migrert fra websphere til wildfly
=> Byttet url til TPS for egenansatt

src/main/java/no/nav/veilarbperson/client/pam/CvIkkeTilgang.java, src/main/java/no/nav/veilarbperson/client/pam/PamClient.java, src/main/java/no/nav/veilarbperson/client/pam/PamClientImpl.java, src/main/java/no/nav/veilarbperson/client/veilarboppfolging/UnderOppfolging.java, src/main/java/no/nav/veilarbperson/client/veilarboppfolging/VeilarboppfolgingClient.java, src/main/java/no/nav/veilarbperson/client/veilarboppfolging/VeilarboppfolgingClientImpl.java, src/main/java/no/nav/veilarbperson/config/CacheConfig.java, src/main/java/no/nav/veilarbperson/config/ClientConfig.java, src/main/java/no/nav/veilarbperson/controller/PersonController.java, src/main/java/no/nav/veilarbperson/service/CvJobbprofilService.java, src/main/java/no/nav/veilarbperson/service/PersonService.java, src/test/java/no/nav/veilarbperson/TestApplicationTest.java, src/test/java/no/nav/veilarbperson/client/DkifClientImplTest.java, src/test/java/no/nav/veilarbperson/client/PamClientImplTest.java, src/test/java/no/nav/veilarbperson/client/VeilarboppfolgingClientImplTest.java, src/test/java/no/nav/veilarbperson/config/ClientTestConfig.java, src/test/java/no/nav/veilarbperson/config/ServiceTestConfig.java, src/test/java/no/nav/veilarbperson/service/CvJobbprofilServiceTest.java, src/test/java/no/nav/veilarbperson/service/PersonServiceTest.java, src/test/java/no/nav/veilarbperson/service/PersonV2ServiceTest.java, src/test/resources/veilarboppfolging-underoppfolging.json
Integrer mot nytt endepunkt hos PAM hvor vi tar hånd om deler av tilgangskontrollen. Sjekk på om bruker har satt hjemmel blir gjort hos PAM.
=> Tilgangskontroll CV/jobbprofil

src/main/java/no/nav/veilarbperson/service/PersonV2Service.java, src/main/java/no/nav/veilarbperson/utils/PersonV2DataMapper.java
Bytter kilde på sikkerhetstiltak fra veilarbportefolje til PDL
=> TC-64 henter sikkerhetstiltak fra pdl og ikke veilarbportefolje

src/main/java/no/nav/veilarbperson/config/EnvironmentProperties.java, src/main/java/no/nav/veilarbperson/config/FilterConfig.java, src/main/resources/application.properties
For å støtte kall med AzureAD OBO-tokens
=> Lager naisAzureAdConfig

nais-dev.yaml, nais-prod.yaml, src/main/java/no/nav/veilarbperson/service/AuthService.java
Også skrevet litt mer oversiktlig med tanke på om det er intern, ekstern eller -systembruker
=> Bruk 'NAVident'-claim om dette er satt

src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
Uavhengig av diskresjonskode og skjerming.
=> Slår opp geografisk enhet

src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
Dette burde testes mot frontend i q1
=> TC-55 bytter fra 404 til 204 for informasjon som ikke finnes i pdl

src/main/java/no/nav/veilarbperson/config/ClientConfig.java
Tilgang er gitt i produksjon: https://github.com/navikt/pam-cv-api/actions/runs/3089854670
=> STS mot CV

src/main/java/no/nav/veilarbperson/config/FilterConfig.java
Merges etter: 
- https://github.com/navikt/veilarbdialog/pull/217
- https://github.com/navikt/veilarbaktivitet/pull/512
=> Fjerner naisStsAuthConfig

nais-dev.yaml, nais-prod.yaml, src/main/java/no/nav/veilarbperson/config/ClientConfig.java, src/main/java/no/nav/veilarbperson/config/EnvironmentProperties.java, src/main/resources/application.properties
Gjorde dette litt kjapt, resten tas i en annen PR
=> Flytt noen URLer og token scopes til yaml-filer

pom.xml
Reverts navikt/veilarbperson#232
=> Revert "Prodsette"

nais-dev.yaml
`*.dev.intern.nav.no` skal byttes ut med `*.intern.dev.nav.no` ref: https://app.slack.com/client/T5LNAMWNA/C01DE3M9YBV/thread/C01DE3M9YBV-1677747333.208699
Endrer derfor til ny URL for veilarbregistrering
=> Endrer URL for veilarbregistrering til intern.dev.nav.no

nais-dev.yaml, nais-prod.yaml, src/main/java/no/nav/veilarbperson/client/pam/PamClientImpl.java, src/test/java/no/nav/veilarbperson/client/PamClientImplTest.java
Reverts navikt/veilarbperson#293
=> Revert "Oppdatere url for pam-cv-api"

nais-dev-gcp.yaml, nais-prod-gcp.yaml
=> Rut kall til veilarboppfolging i gcp

pom.xml, src/main/java/no/nav/veilarbperson/config/SelftTestConfig.java
Bumpe common-pakken slik av vi får ny og korrekt url for healthcheck mot norg2
=> Fikse norg2 healthcheck

nais-dev-gcp.yaml, nais-prod-gcp.yaml, src/main/java/no/nav/veilarbperson/client/representasjon/RepresentasjonClient.java, src/main/java/no/nav/veilarbperson/client/representasjon/RepresentasjonClientImpl.java, src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
- Byttet ingressen til representasjonen siden de har flyttet sin appen fra fss til gcp.
- Trenger ikke å sende fnr i kryptert format lenger da har jeg fjernet det og sender inn normal ident i string format.
- variabel navn endringer: endret fra kryptertIdent til personIdent
- [Ja ] Ja, jeg/vi har testet i dev
=> Byttet ingressen til kilde representasjonen for å hente fullmakt

src/main/java/no/nav/veilarbperson/service/PersonV2Service.java, src/test/java/no/nav/veilarbperson/service/PersonV2ServiceTest.java
=> Henter ikke kontonummer, setter kontonummer til null.

nais-dev-gcp.yaml, nais-prod-gcp.yaml
=> Legg til inngar i inbound rules

Dockerfile
Fikset den kritiske sårbarheten for "UBUNTU-CVE-2024-38428" etter som nais anbefaler.
Referense til samtale på slack : https://nav-it.slack.com/archives/CN8N938K1/p1738749824582079
- [ Ja ] Ja, jeg/vi har testet i dev
=> Byttet base imaget med google sin distroless etter nais anbefaling

src/main/java/no/nav/veilarbperson/client/pdl/GqlVariables.java, src/main/java/no/nav/veilarbperson/client/pdl/PdlClient.java, src/main/java/no/nav/veilarbperson/client/pdl/PdlClientImpl.java, src/main/java/no/nav/veilarbperson/controller/v3/PersonV3Controller.java, src/main/java/no/nav/veilarbperson/service/PersonV2Service.java, src/main/resources/graphql/hentAdressebeskyttelse.gql, src/test/java/no/nav/veilarbperson/client/PdlClientImplTest.java, src/test/java/no/nav/veilarbperson/config/ClientTestConfig.java, src/test/resources/pdl-hentAdressebeskyttelse-response.json
=> Eget endepunkt for å kun hente ut adressebeskyttelse fra pdl på person

src/main/java/no/nav/veilarbperson/client/pdl/PdlClientImpl.java, src/main/java/no/nav/veilarbperson/config/ClientConfig.java, src/test/java/no/nav/veilarbperson/client/PdlClientImplTest.java, src/test/java/no/nav/veilarbperson/config/PdlClientTestConfig.java
=> Lar pdlClientImpl bruke m2m-token dersom man kaller hentNavn med systembruker

src/main/java/no/nav/veilarbperson/service/PersonV2Service.java, src/test/java/no/nav/veilarbperson/service/PersonV2ServiceTest.java
=> Retter fjerning av element og legger til en test

nais-dev-gcp.yaml, nais-prod-gcp.yaml
=> Add auto-instrumentation

pom.xml
=> Oppgraderte avhengighter

pom.xml
=> Oppgraderte avhengigheter til kotlin og springframework

README.md
=> Endre NAV til Nav
